### ISSUE TITLE
[-] error loading file：invalid record

### ISSUE THREAD

**Issue by sun-ruijiang** [chenyueqi/hotBPF#2]
sung@ubuntu:~/Desktop/hotBPF/src/analyzer$ python run_analyze.py ../../testcase/bug-kobject_add_interna
executing ./build/lib/analyzer --crash-report=../../testcase/bug-kobject_add_interna/report --call-graph=../../testcase/bug-kobject_add_interna/report_cg.txt ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/list_debug.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/drivers/base/core.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_sysfs.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_event.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_event.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_core.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/workqueue.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/workqueue.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/kthread.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/arch/x86/entry/entry_64.S.bc 

Total 14 file(s)
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/lib/list_debug.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/drivers/base/core.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_sysfs.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_event.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_event.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_core.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/workqueue.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/workqueue.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/kthread.c.bc'
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/arch/x86/entry/entry_64.S.bc'
Inserting __list_add_valid __list_add
Inserting __list_add list_add_tail
Inserting list_add_tail kobj_kset_join
Inserting kobj_kset_join kobject_add_internal
Inserting kobject_add_internal kobject_add_varg
Inserting kobject_add_varg kobject_add
Inserting kobject_add device_add
Inserting device_add hci_conn_add_sysfs
Inserting hci_conn_add_sysfs hci_conn_complete_evt
Inserting hci_conn_complete_evt hci_event_packet
Inserting hci_event_packet hci_rx_work
Inserting hci_rx_work process_one_work
Inserting process_one_work worker_thread
Inserting worker_thread kthread
Inserting kthread ret_from_fork
[+] Identify crash location as hci_conn_add_sysfs net/bluetooth/hci_sysfs.c:53 explicit checking? 1
analyzer: /home/sung/Desktop/hotBPF/src/analyzer/src/lib/CrashAnalyzer.cc:266: void CrashAnalyzer::dump(llvm::StringRef): Assertion `Ctx->TaintSrc.size() > 0 || Ctx->TmpTaintSrc.size() > 0' failed.
 #0 0x00000000005eab1f llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/home/sung/Desktop/hotBPF/src/analyzer/build/lib/analyzer+0x5eab1f)
 #1 0x00000000005e8da2 llvm::sys::RunSignalHandlers() (/home/sung/Desktop/hotBPF/src/analyzer/build/lib/analyzer+0x5e8da2)
 #2 0x00000000005eb395 SignalHandler(int) (/home/sung/Desktop/hotBPF/src/analyzer/build/lib/analyzer+0x5eb395)
 #3 0x00007f0c5e55d420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007f0c5e04c00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007f0c5e02b859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007f0c5e02b729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007f0c5e03cfd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000000000575dc3 CrashAnalyzer::dump(llvm::StringRef) /home/sung/Desktop/hotBPF/src/analyzer/src/lib/CrashAnalyzer.cc:0:3
 #9 0x0000000000575bb8 CrashAnalyzer::dump() /home/sung/Desktop/hotBPF/src/analyzer/src/lib/CrashAnalyzer.cc:249:54
#10 0x000000000053a208 main /home/sung/Desktop/hotBPF/src/analyzer/src/lib/KAMain.cc:287:10
#11 0x00007f0c5e02d083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#12 0x00000000005385fe _start (/home/sung/Desktop/hotBPF/src/analyzer/build/lib/analyzer+0x5385fe)
Stack dump:
0.	Program arguments: ./build/lib/analyzer --crash-report=../../testcase/bug-kobject_add_interna/report --call-graph=../../testcase/bug-kobject_add_interna/report_cg.txt ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/list_debug.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/lib/kobject.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/drivers/base/core.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_sysfs.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_event.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_event.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/net/bluetooth/hci_core.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/workqueue.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/workqueue.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/kthread.c.bc ../../testcase/bug-kobject_add_interna/linux-bitcode/arch/x86/entry/entry_64.S.bc 
Aborted (core dumped)
Traceback (most recent call last):
  File "run_analyze.py", line 68, in <module>
    run_case(sys.argv[1])
  File "run_analyze.py", line 65, in run_case
    shutil.copyfile("/tmp/ca_result", case_path+"/sts.txt")
  File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ca_result'

**Comment by brant-ruan** [comment]
I encounter the same issue. Actually, I found that the version of clang built from [LLVM-O0-BitcodeWriter](https://github.com/Markakd/LLVM-O0-BitcodeWriter) is `clang version 11.0.0`, which is also used to compile the 5.8 kernel and generate the bitcode, while the version used to build the analyzer is llvm-10. After debugging, the message of the 'error loading file' in the analyzer's output is `invalid record`. Hence, maybe there are some differences or incompatible data between llvm-10 and llvm-11?

But anyway, the analyzer can not be built with llvm-11:

firstly you will come across:

```
In file included from /home/rambo/pjts/hotBPF/src/analyzer/src/lib/Annotation.cc:25:
/home/rambo/pjts/hotBPF/src/analyzer/src/lib/Annotation.h:147:38: error: no member named 'getCalledValue' in 'llvm::CallInst'
    std::string sID = getValueId(CI->getCalledValue());
                                 ~~  ^
/home/rambo/pjts/hotBPF/src/analyzer/src/lib/Annotation.cc:499:23: error: no member named 'getCalledValue' in 'llvm::CallInst'
      Value *CV = CI->getCalledValue();
                  ~~  ^
2 errors generated.
make[3]: *** [lib/CMakeFiles/analyzer.dir/build.make:104: lib/CMakeFiles/analyzer.dir/Annotation.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/rambo/pjts/hotBPF/src/analyzer/src/lib/CallGraph.cc:22:
/home/rambo/pjts/hotBPF/src/analyzer/src/lib/Annotation.h:147:38: error: no member named 'getCalledValue' in 'llvm::CallInst'
    std::string sID = getValueId(CI->getCalledValue());
                                 ~~  ^
/home/rambo/pjts/hotBPF/src/analyzer/src/lib/CallGraph.cc:276:23: error: no member named 'getCalledValue' in 'llvm::CallInst'
    findFunctions(CI->getCalledValue(), FS);
                  ~~  ^
/home/rambo/pjts/hotBPF/src/analyzer/src/lib/CallGraph.cc:326:28: error: no member named 'getCalledValue' in 'llvm::CallInst'
  return findFunctions(CI->getCalledValue(), FS);
                       ~~  ^
3 errors generated.
```

We can use `sed -i 's/getCalledValue/getCalledOperand/g' src/lib/*` to pass it, but will find new issues like:

```
/home/rambo/pjts/hotBPF/src/analyzer/src/lib/StructFinder.cc:43:22: error: no matching member function for call to 'find'
  if (Ctx->CallGraph.find(fName) != Ctx->CallGraph.end()) {
      ~~~~~~~~~~~~~~~^~~~
/home/rambo/pjts/hotBPF/src/analyzer/src/lib/StructFinder.cc:45:29: error: no viable overloaded operator[] for type 'std::map<string, string>' (aka 'map<basic_string<char>, basic_string<char>>')
           << Ctx->CallGraph[fName] << "\n");
              ~~~~~~~~~~~~~~^~~~~~
/home/rambo/pjts/hotBPF/src/analyzer/src/lib/StructFinder.cc:582:10: error: no matching member function for call to 'open'
  result.open(outFile);
  ~~~~~~~^~~~
```

BTW, I also checked the generated bitcode with llvm-bcanalyzer from llvm-10 & llvm-11, and it seems OK:

```
llvm-bcanalyzer net/bluetooth/hci_sysfs.c.bc -dump
```

Hi @chenyueqi, have you encountered similar issues before? Could you please give some suggestions on them?

**Comment by sun-ruijiang** [comment]
Yes, I also found that the LLVM version for compiling the analyzer and building the kernel is inconsistent. This is the main problem that causes errors. At the same time, I have some files that do not exist. I don’t know how to solve this.
Perhaps it is building the kernel with llvm-10 instead of llvm-11？

**Comment by brant-ruan** [comment]
> Yes, I also found that the LLVM version for compiling the analyzer and building the kernel is inconsistent. This is the main problem that causes errors. At the same time, I have some files that do not exist. I don’t know how to solve this.
> Perhaps it is building the kernel with llvm-10 instead of llvm-11？

If you mean the `/tmp/ca_result`, I think it is unnecessary, as the output of analyzer is just the name of structure(s). You can just provide the name(s) as argument for [step 5](https://github.com/chenyueqi/hotBPF/tree/master#step-5-obtain-allocation-sites-of-vulnerable-structures).

Good idea, maybe we can try to apply the patch for O0 bitcode on llvm-10 and recompile the kernel with the customized clang-10.

**Comment by chenyueqi** [comment]
Sorry for the late reply. The desktop that I used for this was accidentally burned out. So I don't have the environment in hand to check the exact version that I used. If I remember it well, LLVM-10 works in general (or at least for this version).

**Comment by chenyueqi** [comment]
Hmm, based on the README file, LLVM-10 works.

**Comment by brant-ruan** [comment]
> Hmm, based on the README file, LLVM-10 works.

Got it, thanks Yueqi. When following the [LLVM-O0-BitcodeWriter](https://github.com/chenyueqi/hotBPF/tree/master#step-5-obtain-allocation-sites-of-vulnerable-structures) repo used in your step1, we will build clang 11:

```
clang version 11.0.0 (https://github.com/llvm/llvm-project 5521236a18074584542b81fd680158d89a845fca)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin
```

I will check whether it works by applying the patch in [LLVM-O0-BitcodeWriter](https://github.com/chenyueqi/hotBPF/tree/master#step-5-obtain-allocation-sites-of-vulnerable-structures) on another clang-10 branch.

**Comment by sun-ruijiang** [comment]
I have used llvm-10 to compile the kernel, but there is still a problem in the fifth step. I don't understand why
```
after@ubuntu:~/Desktop/hotBPF/src/analyzer$ ./build/lib/analyzer -struct hci_conn `find ../../testcase/bug-kobject_add_interna/linux-bitcode/ -name "*.bc"`
Total 6172 file(s)
[-] error loading file '../../testcase/bug-kobject_add_interna/linux-bitcode/kernel/time/timeconst.bc' : 'expected top-level entity'
Killed
```

**Comment by chenyueqi** [comment]
It seems still a version issue. Do you see more warning messages?

**Comment by sun-ruijiang** [comment]
Maybe there is something wrong with my build kernel. I later deleted the file with the problem, and the `IRparse()` function would not report `expected top-level entity`.
